### PR TITLE
complete reformat - better changes

### PR DESCRIPTION
**Pull request by EDM115**
TO-DO :  
+ [x] Better progressbar
+ [x] Make this new version working in Colab
+ [x] Updating the README
+ [x] Updating the Jupyter local script
+ ~~Making `run()` really happening *during* the progressbar edit~~  
`urllib.request.urlopen()` is actually blocking thread, I dont think it will be possible
+ [x] Refactor the other scripts with this version
+ [x] Images are lightweight (better for people with poor connection)

~~DON'T MERGE THIS BRANCH UNTIL I TELL YOU TO DO SO~~  
~~**IT'S STILL A WIP**~~  Finished now, it's mergeable

### CODE REVIEW

**Comment by EDM115** [comment]
still working on the concurrent functions  
also it will be hard to implement this on the Jupyter Notebook as it keeps raising different errors when I tried that version 🥲

**Comment by EDM115** [comment]
fully okay for the Jupyter  
also the original file (https://www.caduceus.ml/files/Warp-on-Jupyter-Server.ipynb) have been removed from the README and replaced with the Warp_on_Jupyter_Server.ipynb file (for logic reasons : that one have the changes)  
  
only thing left is the concurrent things, may be done tomorrow or never... 🥲

**Comment by EDM115** [comment]
so it's no possible to make it better further  
the only thing to do now is to add `pip install nest-asyncio` on your https://github.com/thecaduceus/WLA/pkgs/container/wla (**excepting** if it installs things from the requirements.txt, in such case it's okay

**Comment by EDM115** [comment]
Notes :  
+ The README have been refactored to be more a Markdown file instead of a Website copy-paste
+ I didn't touched the `index.html`, it's up to you to update it regarding to the PR or not
+ The Replit method is no longer available (the script have been deleted ? idk)
+ It fixes every problem from #30 (including [not asking the referrer and using mine instead](https://github.com/TheCaduceus/WARP-UNLIMITED-ADVANCED/pull/30#issuecomment-1302462560))
  
@TheCaduceus it's up to you now 🥺

**Review by TheCaduceus — APPROVED** [review]
**Approved! ✅ You done a very hard work; I appreciate it.**

**Pull request merged**
